-- Requires psql variable "schema_name" to be set, for example:
-- \set schema_name app

CREATE TABLE IF NOT EXISTS account (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    login_attempts INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT account_role_ck CHECK (role IN ('customer', 'admin', 'supplier'))
);

 CREATE TABLE IF NOT EXISTS accountlogin (
	token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id BIGINT NOT NULL,
	token_string TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountlogins_account_fk FOREIGN KEY (account_id) REFERENCES account (account_id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS supplier (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_email TEXT,
    contact_phone TEXT
);

CREATE TABLE IF NOT EXISTS product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (discount_percent >= 0 AND discount_percent <= 100),
    stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT product_supplier_fk FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id)
);

CREATE TABLE IF NOT EXISTS product_image (
    product_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT product_image_product_fk FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    session_key TEXT UNIQUE,
    total_price BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT cart_account_fk FOREIGN KEY (account_id) REFERENCES account (account_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    order_number TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    subtotal_amount NUMERIC(12,2) NOT NULL CHECK (subtotal_amount >= 0),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    placed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT orders_account_fk FOREIGN KEY (account_id) REFERENCES account (account_id),
    CONSTRAINT orders_status_ck CHECK (status IN ('pending', 'paid', 'packed', 'shipped', 'delivered', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS payment (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    payment_method TEXT NOT NULL,
    payment_status TEXT NOT NULL,
    transaction_ref TEXT UNIQUE,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    paid_at TIMESTAMPTZ,
    CONSTRAINT payment_order_fk FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT payment_method_ck CHECK (payment_method IN ('card', 'eft', 'cash_on_delivery', 'wallet')),
    CONSTRAINT payment_status_ck CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded'))
);

CREATE TABLE IF NOT EXISTS shipment (
    shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    courier_name TEXT,
    courier_type TEXT,
    delivery_reference TEXT UNIQUE,
    delivery_address_line1 TEXT NOT NULL,
    delivery_address_line2 TEXT,
    delivery_city TEXT NOT NULL,
    delivery_state TEXT,
    delivery_postal_code TEXT NOT NULL,
    delivery_country TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    recipient_phone TEXT,
    shipment_status TEXT NOT NULL,
    dispatched_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT shipment_order_fk FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT shipment_status_ck CHECK (shipment_status IN ('pending', 'dispatched', 'in_transit', 'delivered', 'failed', 'returned')),
    CONSTRAINT shipment_delivery_time_ck CHECK (delivered_at IS NULL OR dispatched_at IS NULL OR delivered_at >= dispatched_at)
);

CREATE TABLE IF NOT EXISTS cart_item (
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (cart_id, product_id),
    CONSTRAINT cart_item_cart_fk FOREIGN KEY (cart_id) REFERENCES cart (cart_id) ON DELETE CASCADE,
    CONSTRAINT cart_item_product_fk FOREIGN KEY (product_id) REFERENCES product (product_id)
);

CREATE TABLE IF NOT EXISTS order_item (
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT order_item_order_fk FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT order_item_product_fk FOREIGN KEY (product_id) REFERENCES product (product_id)
);

CREATE TABLE IF NOT EXISTS category (
    category_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_product_supplier_id ON product (supplier_id);
CREATE INDEX IF NOT EXISTS idx_product_is_active ON product (is_active);
CREATE INDEX IF NOT EXISTS idx_product_image_product_id ON product_image (product_id);
CREATE INDEX IF NOT EXISTS idx_cart_account_id ON cart (account_id);
CREATE INDEX IF NOT EXISTS idx_orders_account_id ON orders (account_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payment (payment_status);
CREATE INDEX IF NOT EXISTS idx_shipment_status ON shipment (shipment_status);
CREATE INDEX IF NOT EXISTS idx_cart_item_product_id ON cart_item (product_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product_id ON order_item (product_id);
CREATE INDEX IF NOT EXISTS idx_category_is_active ON :"schema_name".category (is_active);
CREATE INDEX IF NOT EXISTS idx_product_category_id ON :"schema_name".product (category_id);
